version: '2'
services:
  web:
    build: .
    ports:
        - "5000:5000"
    volumes:
        - .:/code
    links:
        - redis
    environment:
        - FLASK_ENV=development

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
